FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Копируем JAR файл (должен быть собран заранее)
COPY report-generator/build/libs/report-generator-*.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]