FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Копируем JAR файл (должен быть собран заранее)
COPY db-planny-service/build/libs/db-planny-service-*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]