FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Копируем JAR файл (должен быть собран заранее)
COPY tg-bot-planny/build/libs/tg-bot-planny-*.jar app.jar

EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]